version: "2"
services:

  auth:
    image: carlosmecha/nginx-auth
    ports:
      - "8081:80"

  site:
    image: carlosmecha/nginx-site
    ports:
      - "8082:80"

  nginx:
    image: carlosmecha/nginx
    depends_on:
      - site
      - auth
    ports:
      - "8080:80"